version: '3.9'

services:
  db:
    image: postgres:17
    container_name: database
    restart: unless-stopped
    networks:
      - bookstore
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432 -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bookstore:
    name: bookstore